apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: neuroran-agent
  namespace: neuroran
spec:
  selector:
    matchLabels:
      app: neuroran
  template:
    metadata:
      labels:
        app: neuroran
    spec:
      containers:
        - name: neuroran
          image: neuroran-dev:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: policy
              mountPath: /etc/neuroran
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: policy
          configMap:
            name: neuroran-policy
      hostPID: true
      restartPolicy: Always
